### ISSUE TITLE
Uninitialized constant SolidQueueDashboard::PaginationHelper::OpenStruct

### ISSUE THREAD

**Issue by erlingur** [akodkod/solid-queue-dashboard#1]
Was just trying out this gem in a fresh Rails 8 beta project and I get this error when opening the Jobs page.

uninitialized constant SolidQueueDashboard::PaginationHelper::OpenStruct

Trace:
```
[solid_queue_dashboard (0.1.0) app/helpers/solid_queue_dashboard/pagination_helper.rb:13:in `paginate'](http://localhost:3000/solid-queue/jobs#)
[solid_queue_dashboard (0.1.0) app/controllers/solid_queue_dashboard/jobs_controller.rb:34:in `set_jobs'](http://localhost:3000/solid-queue/jobs#)
```

Adding `gem "ostruct"` to the main app Gemfile resolves this. Maybe it should be a dependency?

This looks great btw! Really nice, great job 👍🏻

**Comment by akodkod** [comment]
@erlingur, thank you so much for your feedback and for writing such a well-crafted issue.

I’ve resolved it by replacing OpenStruct with a simple hash. New version is already available.

**Comment by erlingur** [comment]
Hey no problem, my pleasure :) Can confirm it's fixed, thanks! 👍🏻
